spring:
  application:
    name: ytts

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sajtkrem
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
