spring:
  application:
    name: ytts

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sajtkrem
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
